---
- name: Ensure server config
  ansible.builtin.template:
    src: "{{ ssh_sshd_config_file_template }}"
    dest: "{{ ssh_sshd_config_file }}"
    owner: root
    group: root
    mode: "0644"
  notify: Reload SSH daemon
  become: true
  tags: sshd_config
