---
- name: Ensure users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default(ssh_default_user_shell) }}"
    state: "{{ item.state | default(ssh_default_user_state) }}"
    group: "{{ item.group | default(ssh_default_user_group) }}"
    groups: "{{ item.groups | default(None) }}"
    remove: '{% if item.state | default(ssh_default_user_state) == "absent" %}yes{% else %}no{% endif %}'
  with_items: "{{ ssh_users }}"
  become: true
  tags: ssh_users

- name: Ensure authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  when: 'item.state | default(ssh_default_user_state) == "present"'
  with_items: "{{ ssh_users }}"
  become: true
  tags: ssh_users
