---
- name: Ensure users
  user:
    name: '{{ item.name }}'
    state: '{{ item.state | default(ssh_default_user_state) }}'
    group: '{{ item.group | default(ssh_default_user_group) }}'
    remove: '{% if item.state | default(ssh_default_user_state) == "absent" %}yes{% else %}no{% endif %}'
  with_items: ssh_users

- name: Ensure Git SSH
  run_once: true
  connection: local
  become: false
  get_url:
    url: '{{ ssh_git_url }}/{{ item.git_name | default(item.name) }}.keys'
    dest: '/tmp/{{ item.name }}.authorized_keys'
    mode: '0664'
    force: true
  when: '"{{ item.state | default(ssh_default_user_state)}}" == "present" and item.key is not defined and ssh_git_url is defined'
  with_items: '{{ ssh_users }}'

- name: Ensure SSH key
  run_once: true
  connection: local
  become: false
  copy:
    dest: '/tmp/{{ item.name }}.authorized_keys'
    content: '{{ item.key }}'
    mode: '0664'
  when: item.key is defined
  with_items: ssh_users

- name: Ensure authorized_keys
  authorized_key:
    user: '{{ item.name }}'
    key: '{{ lookup("file", "/tmp/"+ item.name +".authorized_keys") }}'
  when: '"{{ item.state | default(ssh_default_user_state) }}" == "present"'
  with_items: ssh_users
